services:
  - type: web
    name: expence-tracker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn expencetracker.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: expencetracker.settings
      - key: PYTHON_VERSION
        value: 3.12
