# Generated by Django 4.1 on 2025-07-16 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trackinghistory',
            old_name='expence_type',
            new_name='expense_type',
        ),
    ]
